In [18]:
import numpy as np
from numpy import asarray

data = [[3, 3, 2, 1, 0],
        [0, 0, 1, 3, 1],
        [3, 1, 2, 2, 3],
        [2, 0, 0, 2, 2],
        [2, 0, 0, 0, 1]]
data = np.asarray(data)
data = data.reshape(1, 5, 5, 1) # get 5 x 5 

kernel = [[[[0]], [[1]], [[2]]],
          [[[2]], [[2]],[[0]]],
          [[[0]], [[1]], [[2]]]]

weights = [asarray(kernel), asarray([0.0])]

In [19]:
print(data)

[[[[3]
   [3]
   [2]
   [1]
   [0]]

  [[0]
   [0]
   [1]
   [3]
   [1]]

  [[3]
   [1]
   [2]
   [2]
   [3]]

  [[2]
   [0]
   [0]
   [2]
   [2]]

  [[2]
   [0]
   [0]
   [0]
   [1]]]]


In [20]:
print(kernel)

[[[[0]], [[1]], [[2]]], [[[2]], [[2]], [[0]]], [[[0]], [[1]], [[2]]]]


In [44]:
from keras.models import Sequential
from keras.layers import Conv2D

# Create model
## KERNEL
model = Sequential()
model.add(Conv2D(1, (3,3), input_shape=(5, 5, 1)))
print(model.summary())
print('-----------------------------------------------------------------------------------------------------------------------')
model.set_weights(weights)
yhat = model.predict(data)
print('the output is :')
print('---------------')
for r in range(yhat.shape[1]):
    print([yhat[0, r, c, 0] for c in range(yhat.shape[2])])

Model: "sequential_21"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_21 (Conv2D)           (None, 3, 3, 1)           10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________
None
-----------------------------------------------------------------------------------------------------------------------
the output is :
---------------
[12.0, 12.0, 17.0]
[10.0, 17.0, 19.0]
[9.0, 6.0, 14.0]


In [45]:
## Stride
model = Sequential()
model.add(Conv2D(1, (3,3), strides=(2,2), input_shape=(5, 5, 1)))
print(model.summary())
print('-----------------------------------------------------------------------------------------------------------------------')
model.set_weights(weights)
yhat = model.predict(data)
print('the output is :')
print('---------------')
for r in range(yhat.shape[1]):
    print([yhat[0, r, c, 0] for c in range(yhat.shape[2])])

Model: "sequential_22"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_22 (Conv2D)           (None, 2, 2, 1)           10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________
None
-----------------------------------------------------------------------------------------------------------------------
the output is :
---------------
[12.0, 17.0]
[9.0, 14.0]


In [46]:
## Padding
model = Sequential()
model.add(Conv2D(1, (3,3), padding='same', input_shape=(5, 5, 1)))
print(model.summary())
print('-----------------------------------------------------------------------------------------------------------------------')
model.set_weights(weights)
yhat = model.predict(data)
print('the output is :')
print('---------------')
for r in range(yhat.shape[1]):
    print([yhat[0, r, c, 0] for c in range(yhat.shape[2])])

Model: "sequential_23"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_23 (Conv2D)           (None, 5, 5, 1)           10        
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________
None
-----------------------------------------------------------------------------------------------------------------------
the output is :
---------------
[6.0, 14.0, 17.0, 11.0, 3.0]
[14.0, 12.0, 12.0, 17.0, 11.0]
[8.0, 10.0, 17.0, 19.0, 13.0]
[11.0, 9.0, 6.0, 14.0, 12.0]
[6.0, 4.0, 4.0, 6.0, 4.0]


In [49]:
## Max Pooling
from keras.layers import MaxPooling2D
model = Sequential()
model.add(Conv2D(1, (3,3), padding='same', input_shape=(5, 5, 1)))
model.add(MaxPooling2D((2, 2)))
print(model.summary())
print('-----------------------------------------------------------------------------------------------------------------------')
model.set_weights(weights)
yhat = model.predict(data)
print('the output is :')
print('---------------')
for r in range(yhat.shape[1]):
    print([yhat[0, r, c, 0] for c in range(yhat.shape[2])])

Model: "sequential_26"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_26 (Conv2D)           (None, 5, 5, 1)           10        
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 2, 2, 1)           0         
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________
None
-----------------------------------------------------------------------------------------------------------------------
the output is :
---------------
[14.0, 17.0]
[11.0, 19.0]


In [50]:
## Average Pooling
from keras.layers import AveragePooling2D
model = Sequential()
model.add(Conv2D(1, (3,3), padding='same', input_shape=(5, 5, 1)))
model.add(AveragePooling2D((2, 2)))
print(model.summary())
print('-----------------------------------------------------------------------------------------------------------------------')
model.set_weights(weights)
yhat = model.predict(data)
print('the output is :')
print('---------------')
for r in range(yhat.shape[1]):
    print([yhat[0, r, c, 0] for c in range(yhat.shape[2])])

Model: "sequential_27"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_27 (Conv2D)           (None, 5, 5, 1)           10        
_________________________________________________________________
average_pooling2d (AveragePo (None, 2, 2, 1)           0         
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________
None
-----------------------------------------------------------------------------------------------------------------------
the output is :
---------------
[11.5, 14.25]
[9.5, 14.0]


In [51]:
# Flatten
from keras.layers import Flatten

model = Sequential()
model.add(Conv2D(1, (3,3), padding='same', input_shape=(5, 5, 1)))
model.add(AveragePooling2D((2, 2)))
model.add(Flatten())
model.summary()

Model: "sequential_28"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_28 (Conv2D)           (None, 5, 5, 1)           10        
_________________________________________________________________
average_pooling2d_1 (Average (None, 2, 2, 1)           0         
_________________________________________________________________
flatten (Flatten)            (None, 4)                 0         
Total params: 10
Trainable params: 10
Non-trainable params: 0
_________________________________________________________________
